### ISSUE TITLE
outdated bower package

### ISSUE THREAD

**Issue by GlauberF** [assisrafael/bower-angular-input-masks#3]
the package is outdated in relation to angular-input-masks, the angular-input-masks version is already in v4.2.1 and here it is in version 2.6.0

Needs to be updated to support versions

**Comment by assisrafael** [comment]
Bower is no longer supported since version 3.0. I have updated the README to reflect this situation.

**Comment by GlauberF** [comment]
right, is there any standalone file, where can I call only this file in my project?
version 4.x
